name: Linked_data_app
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h4f5f683_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - altair=6.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - arrow=1.4.0=pyhcf101f3_0
  - astroid=4.0.2=py313hfa70ccb_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - asyncssh=2.21.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - backports.zstd=1.2.0=py313h2a31948_0
  - bcrypt=5.0.0=py313hfbe8231_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=25.12.0=pyh866005b_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py313h3ebfc14_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cattrs=25.3.0=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h5ea7bf4_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.13.11=py313hd8ed1ab_100
  - cryptography=46.0.3=py313hf5c5e30_1
  - dataclasses-json=0.6.7=pyhcf101f3_2
  - debugpy=1.8.19=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.0=pyhcf101f3_1
  - distro=1.9.0=pyhd8ed1ab_1
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - frozenlist=1.7.0=py313h0c48a3b_0
  - fzf=0.67.0=hb13f615_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.86.3=h19e2e61_0
  - glib-tools=2.86.3=he647baa_0
  - greenlet=3.3.0=py313hfe59770_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - httpx-sse=0.4.3=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.31.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isort=7.0.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.4.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.2.1=py313hf61f64f_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jiter=0.12.0=py313hf61f64f_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=25.7.0=pyh7428d3b_0
  - krb5=1.21.3=hdf4eb48_0
  - langchain=1.2.0=pymin313_h332efcf_0
  - langchain-community=0.3.31=pymin312_hd8ed1ab_1
  - langchain-core=1.2.4=pyhd8ed1ab_0
  - langchain-text-splitters=0.3.11=pyhd8ed1ab_0
  - langgraph=1.0.5=pyhd8ed1ab_0
  - langgraph-checkpoint=3.0.1=pyhcf101f3_0
  - langgraph-prebuilt=1.0.5=pyhcf101f3_0
  - langgraph-sdk=0.3.1=pyhcf101f3_0
  - langsmith=0.5.0=pyhd8ed1ab_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h89d7da9_6_cpu
  - libarrow-acero=22.0.0=h7d8d6a5_6_cpu
  - libarrow-compute=22.0.0=h2db994a_6_cpu
  - libarrow-dataset=22.0.0=h7d8d6a5_6_cpu
  - libarrow-substrait=22.0.0=hf865cc0_6_cpu
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_2
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libogg=1.3.5=h2466b09_1
  - libparquet=22.0.0=h7051d1f_6_cpu
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.2=hb980946_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lsprotocol=2025.0.0=pyhe01879c_0
  - lz4-c=1.10.0=h2466b09_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py313hd650c13_0
  - marshmallow=3.26.1=pyhd8ed1ab_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - more-itertools=10.8.0=pyhcf101f3_1
  - multidict=6.7.0=py313hd650c13_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.14.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hc388f54_1
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbconvert-pandoc=7.16.6=h7d6f222_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.0=py313hce7ae62_0
  - numpydoc=1.10.0=pyhcf101f3_0
  - openai=1.109.1=pyhd8ed1ab_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - orjson=3.11.4=py313hfbe8231_1
  - ormsgpack=1.12.1=py313h58076df_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_2
  - pandoc=3.8.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.47=hd2b5f0e_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py313h38f99e1_2
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313hb4c8b1a_0
  - protobuf=6.31.1=py313h16c7a9f_2
  - psutil=7.1.3=py313h5fd188c_0
  - pthread-stubs=0.4=h0e40799_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py313hfa70ccb_0
  - pyarrow-core=22.0.0=py313h5921983_0_cpu
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py313hfbe8231_1
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pylint=4.0.4=pyhcf101f3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.1=py313h5ea7bf4_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyqt=5.15.11=py313h1048830_2
  - pyqt5-sip=12.17.0=py313hfe59770_2
  - pyqtwebengine=5.15.11=py313hbf4b574_2
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.11=h09917c8_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.13.11=h4df99d1_100
  - python-gssapi=1.10.1=py313h6caa264_1
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-ruff=2.3.0=pyhcf101f3_0
  - python-lsp-server=1.14.0=pyh332efcf_0
  - python-lsp-server-base=1.14.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py313hdf96bf3_1
  - python_abi=3.13=8_cp313
  - pytokens=0.3.0=pyhcf101f3_0
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py313h40c08fc_1
  - pywin32-ctypes=0.2.3=py313hfa70ccb_3
  - pyyaml=6.0.3=py313hd650c13_0
  - pyzmq=27.0.2=py313hdb570cd_1
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=hb098fff_6
  - qt-webengine=5.15.15=h087ee03_1
  - qtawesome=1.4.0=pyh9208f05_1
  - qtconsole=5.7.0=pyhd8ed1ab_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - qtpy=2.4.3=pyhd8ed1ab_1
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - roman-numerals=4.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.30.0=py313hfbe8231_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.14.10=h37e10c4_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py313hfe59770_1
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sphinx=9.0.4=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.1.2=hd8ed1ab_0
  - spyder-base=6.1.2=py313hfa70ccb_0
  - spyder-kernels=3.1.2=win_pyh7428d3b_0
  - sqlalchemy=2.0.45=py313h5ea7bf4_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - streamlit=1.52.2=pyhd8ed1ab_0
  - superqt=0.7.6=pyhb6d5dde_0
  - tbb=2022.3.0=hd094cb3_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.4=py313h5ea7bf4_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.11.0=py313h927ade5_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - uuid-utils=0.12.0=py310h9ee1adf_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - watchdog=6.0.0=py313hfa70ccb_2
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py313h5ea7bf4_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.22.0=py313hd650c13_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstandard=0.25.0=py313h5fd188c_1
  - zstd=1.5.7=h534d264_6
  - pip:
    - anthropic==0.75.0
    - bracex==2.6
    - deepagents==0.3.0
    - docstring-parser==0.17.0
    - et-xmlfile==2.0.0
    - filetype==1.2.0
    - google-auth==2.45.0
    - google-genai==1.56.0
    - langchain-anthropic==1.3.0
    - langchain-google-genai==4.1.2
    - langchain-openai==1.1.6
    - mcp==1.25.0
    - openpyxl==3.1.5
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - python-multipart==0.0.21
    - regex==2025.11.3
    - rsa==4.9.1
    - sse-starlette==3.0.4
    - starlette==0.50.0
    - tiktoken==0.12.0
    - uvicorn==0.40.0
    - wcmatch==10.1
    - websockets==15.0.1